services:
  api:
    image: vinylpi/api:latest
    environment:
      WEB_URL: http://localhost:3000
      PLAYER_NAME: "VinylPi"
    env_file:
      - spotify.env
    ports:
      - "5000:80"

  web:
    image: vinylpi/web:latest
    ports:
      - "3000:80"
